name: SkyBlockPE
main: MyPlot\MyPlot
version: 1.1.6
api:
- 3.0.0
- 3.0.0-ALPHA7
authors:
 - Wiez
 - Exxarion
 - jasonwynn10
 - XenialDan
description: "SkyBlock recoded for MCPE based on MyPlot"
load: STARTUP
softdepend:
- EconomyAPI
- PocketMoney
- EssentialsPE
- EconomyPlus
extensions:
- sqlite3
- mysqli
- yaml
permissions:
    skyblock.command:
        default: op
        children:
            skyblock.command.help:
                default: true
            skyblock.command.claim:
                default: true
            skyblock.command.info:
                default: true
            skyblock.command.generate:
                default: op
            skyblock.command.addhelper:
                default: true
            skyblock.command.removehelper:
                default: true
            skyblock.command.denyplayer:
                default: true
            skyblock.command.undenyplayer:
                default: true
            skyblock.command.auto:
                default: true
            skyblock.command.clear:
                default: true
            skyblock.command.dispose:
                default: true
            skyblock.command.reset:
                default: true
            skyblock.command.biome:
                default: true
            skyblock.command.biomes:
                default: true
            skyblock.command.home:
                default: true
            skyblock.command.homes:
                default: true
            skyblock.command.name:
                default: true
            skyblock.command.give:
                default: true
            skyblock.command.warp:
                default: true
            skyblock.command.done:
                default: true
            skyblock.command.middle:
                default: true
            skyblock.command.list:
                default: true
    skyblock.admin:
        default: op
        children:
            skyblock.admin.clear:
                default: op
            skyblock.admin.biome:
                default: op
            skyblock.admin.biomes:
                defualt: op
            skyblock.admin.dispose:
                default: op
            skyblock.admin.reset:
                default: op
            skyblock.admin.addhelper:
                default: op
            skyblock.admin.removehelper:
                default: op
            skyblock.admin.denyplayer:
                default: op
            skyblock.admin.undenyplayer:
                default: op
            skyblock.admin.bypassdeny:
                default: op
            skyblock.admin.build:
                default: op
                children:
                    skyblock.admin.build.plot:
                        default: op
                    skyblock.admin.build.road:
                        default: op
            skyblock.admin.name:
                default: op
            skyblock.admin.warp:
                default: op
            skyblock.admin.done:
                default: op
            skyblock.admin.middle:
                default: true
            skyblock.admin.list:
                default: op
    skyblock.claimplots:
        default: op
        children:
            skyblock.claimplots.2:
                default: true
            skyblock.claimplots.unlimited:
                default: op
